In [154]:
import pandas as pd
import io

In [2]:
from google.colab import files
 
 
uploaded = files.upload()

Saving Bihar_Election_Results .csv to Bihar_Election_Results .csv

In [155]:
df = pd.read_csv(io.BytesIO(uploaded['Bihar_Election_Results .csv']))

****Q1****

In [157]:
df1 = df.groupby(['Election Year','Party']).sum().reset_index()
# Q1 = df1.loc[df1.groupby(['Election Year'])['Votes'].idxmax()].reset_index()
# print(Q1)
df1['Winning_rank'] = df1.groupby(['Election Year'])['Votes'].rank(ascending=False)
df1.loc[df1['Winning_rank'] == 1.0]

,Election Year,Party,Position,Votes,AC No,Winning_rank
50,2005-Feb,Rashtriya Janata Dal,431,6140223,25719,1.0
111,2005-Oct,Rashtriya Janata Dal,319,5525081,21364,1.0
168,2010,Janata Dal (United),172,6561906,17669,1.0
244,2015,Bharatiya Janta Party,263,9308015,17747,1.0

**Q2**

In [134]:
df_2 =df.groupby(['Election Year','AC No', 'Party']).sum().reset_index()
df_2['Winning_rank'] = df_2.groupby(['Election Year','AC No'])['Votes'].rank(ascending=False)
# df_2.sort_values(by = ['Election Year','AC No', 'Winning_rank'])
df_3 = df_2.loc[df_2['Winning_rank'] == 1.0].sort_values(by = ['AC No','Election Year'])
# df_3.sort_values(by = ['AC No', 'Election Year'])
df_4 = df_3.groupby(['AC No']).nunique()
len(df_4.loc[df_4['Party'] == 4])

22

**Q3**

In [159]:
Q3 = df1.loc[df1['Winning_rank'] <= 8.0].sort_values(by =['Election Year','Winning_rank'])
print(Q3)

    Election Year                             Party  Position    Votes  \
50       2005-Feb              Rashtriya Janata Dal       431  6140223
20       2005-Feb                       Independent     15010  3957945
27       2005-Feb               Janata Dal (United)       318  3564930
37       2005-Feb              Lok Jan Shakti Party       585  3091173
13       2005-Feb             Bharatiya Janta Party       226  2686290
22       2005-Feb          Indian National Congress       305  1223835
10       2005-Feb               Bahujan Samaj Party      1434  1080745
58       2005-Feb                   Samajwadi Party      1167   658791
111      2005-Oct              Rashtriya Janata Dal       319  5525081
95       2005-Oct               Janata Dal (United)       209  4819759
80       2005-Oct             Bharatiya Janta Party       173  3686720
102      2005-Oct              Lok Jan Shakti Party       669  2615901
87       2005-Oct                       Independent      5505  2065744
89       2005-Oct          Indian National Congress       104  1435449
76       2005-Oct               Bahujan Samaj Party      1156   981464
120      2005-Oct                   Samajwadi Party      1002   594266
168          2010               Janata Dal (United)       172  6561906
194          2010              Rashtriya Janata Dal       351  5475656
151          2010             Bharatiya Janta Party       119  4790436
160          2010                       Independent     13098  3842812
162          2010          Indian National Congress      1006  2431477
178          2010              Lok Jan Shakti Party       184  1957232
141          2010               Bahujan Samaj Party      1687   933947
186          2010        Nationalist Congress Party      1614   528575
244          2015             Bharatiya Janta Party       263  9308015
333          2015              Rashtriya Janata Dal       124  6995509
283          2015               Janata Dal (United)       133  6416414
274          2015                       Independent      9993  3580953
275          2015          Indian National Congress        57  2539638
297          2015              Lok Jan Shakti Party        88  1840834
338          2015         Rashtriya Lok Samta Party        48   976787
272          2015  Hindustani Awam Morcha (Secular)        45   864856

      AC No  Winning_rank
50    25719           1.0
20   181641           2.0
27    16825           3.0
37    21837           4.0
13    12280           5.0
22    10190           6.0
10    28913           7.0
58    16483           8.0
111   21364           1.0
95    17158           2.0
80    12351           3.0
102   24204           4.0
87    95176           5.0
89     5737           6.0
76    26484           7.0
120   17285           8.0
168   17669           1.0
194   20664           2.0
151   11837           3.0
160  162144           4.0
162   29506           5.0
178    8842           6.0
141   29085           7.0
186   19905           8.0
244   17747           1.0
333   12401           2.0
283   12289           3.0
274  141150           4.0
275    4816           5.0
297    5489           6.0
338    3161           7.0
272    3109           8.0

**Q4**

In [160]:
df2 = df1[(df1['Election Year'] == '2015') & (df1['Winning_rank'] <= 8.0)]
top_8_2015= df2['Party'].to_list()
df_c = df.loc[(df['Election Year'] != '2015') & (df['Party'].isin(top_8_2015))]
df_c.groupby(['Election Year','Party','AC No']).sum().reset_index()

     Election Year                  Party  AC No  Position  Votes
0         2005-Feb  Bharatiya Janta Party      3         1  20961
1         2005-Feb  Bharatiya Janta Party      4         2  19161
2         2005-Feb  Bharatiya Janta Party      5         3  11672
3         2005-Feb  Bharatiya Janta Party      7         1  27642
4         2005-Feb  Bharatiya Janta Party      8         1  48559
...            ...                    ...    ...       ...    ...
2799          2010   Rashtriya Janata Dal    234         4  10394
2800          2010   Rashtriya Janata Dal    235         2  36930
2801          2010   Rashtriya Janata Dal    237         2  40231
2802          2010   Rashtriya Janata Dal    241         2  35663
2803          2010   Rashtriya Janata Dal    242         2  37876

[2804 rows x 5 columns]

Question **F**

In [161]:
df_5 = df_4.loc[df_4['Party'] == 1].reset_index()
strong_hold = df_5['AC No'].to_list()
df_2.loc[(df_2['Winning_rank'] == 1.0) & (df_2['AC No'].isin(strong_hold))].sort_values(by =['AC No','Election Year'])

,Election Year,AC No,Party,Position,Votes,Winning_rank
57,2005-Feb,7,Bharatiya Janta Party,1,27642,1.0
1981,2005-Oct,7,Bharatiya Janta Party,1,42960,1.0
3605,2010,7,Bharatiya Janta Party,1,44835,1.0
6005,2015,7,Bharatiya Janta Party,1,61304,1.0
67,2005-Feb,8,Bharatiya Janta Party,1,48559,1.0
1987,2005-Oct,8,Bharatiya Janta Party,1,55184,1.0
3617,2010,8,Bharatiya Janta Party,1,42010,1.0
6014,2015,8,Bharatiya Janta Party,1,50768,1.0
204,2005-Feb,25,Bharatiya Janta Party,1,26077,1.0
2100,2005-Oct,25,Bharatiya Janta Party,1,38235,1.0
3786,2010,25,Bharatiya Janta Party,1,32987,1.0
6173,2015,25,Bharatiya Janta Party,1,66388,1.0
324,2005-Feb,41,Janata Dal (United),1,33776,1.0
2222,2005-Oct,41,Janata Dal (United),1,40371,1.0
3938,2010,41,Janata Dal (United),1,70150,1.0
6349,2015,41,Janata Dal (United),1,79600,1.0
2227,2005-Oct,42,Bharatiya Janta Party,1,28634,1.0
554,2005-Feb,72,Janata Dal (United),1,35221,1.0
2405,2005-Oct,72,Janata Dal (United),1,38301,1.0
4208,2010,72,Janata Dal (United),1,72282,1.0
6694,2015,72,Janata Dal (United),1,83073,1.0
785,2005-Feb,105,Bharatiya Janta Party,1,32052,1.0
2611,2005-Oct,105,Bharatiya Janta Party,1,39768,1.0
4539,2010,105,Bharatiya Janta Party,1,51637,1.0
7059,2015,105,Bharatiya Janta Party,1,55156,1.0
843,2005-Feb,112,Janata Dal (United),1,35498,1.0
2662,2005-Oct,112,Janata Dal (United),1,48457,1.0
4621,2010,112,Janata Dal (United),1,40232,1.0
7134,2015,112,Janata Dal (United),1,68459,1.0
2784,2005-Oct,131,Janata Dal (United),1,47758,1.0
978,2005-Feb,132,Janata Dal (United),1,51804,1.0
2791,2005-Oct,132,Janata Dal (United),1,39007,1.0
4800,2010,132,Janata Dal (United),1,46245,1.0
7330,2015,132,Janata Dal (United),1,92687,1.0
1144,2005-Feb,149,Janata Dal (United),1,37784,1.0
2913,2005-Oct,149,Janata Dal (United),1,45646,1.0
4967,2010,149,Janata Dal (United),1,48841,1.0
7497,2015,149,Janata Dal (United),1,64767,1.0
1172,2005-Feb,153,Janata Dal (United),1,50827,1.0
2936,2005-Oct,153,Janata Dal (United),1,48063,1.0
5002,2010,153,Janata Dal (United),1,53876,1.0
7536,2015,153,Janata Dal (United),1,57403,1.0
1228,2005-Feb,160,Janata Dal (United),1,26184,1.0
2976,2005-Oct,160,Janata Dal (United),1,37789,1.0
5079,2010,160,Janata Dal (United),1,40261,1.0
7599,2015,160,Janata Dal (United),1,68858,1.0
1346,2005-Feb,176,Janata Dal (United),1,74752,1.0
3066,2005-Oct,176,Janata Dal (United),1,62634,1.0
5239,2010,176,Janata Dal (United),1,58067,1.0
7756,2015,176,Janata Dal (United),1,72596,1.0
1600,2005-Feb,202,Janata Dal (United),1,21843,1.0
3259,2005-Oct,202,Janata Dal (United),1,32137,1.0
5503,2010,202,Janata Dal (United),1,54802,1.0
8067,2015,202,Janata Dal (United),1,84184,1.0
1726,2005-Feb,215,Janata Dal (United),1,51741,1.0
3352,2005-Oct,215,Janata Dal (United),1,48645,1.0
5668,2010,215,Janata Dal (United),1,37633,1.0
8192,2015,215,Janata Dal (United),1,43676,1.0