In [1]:
# import packages
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import matplotlib
plt.style.use('ggplot')
from matplotlib.pyplot import figure

%matplotlib inline
matplotlib.rcParams['figure.figsize'] = (12,8)

pd.options.mode.chained_assignment = None

In [3]:
df1 = pd.read_excel("HR Dataset.xlsx")

In [4]:
df1.head()

,Serial No,Age,Qualification,Experience,Domain,Skill,Designation,Project,Salary,Rating,ESS,Status
0,1,25,MCA,3,BFSI,Java,SE,Citi Bank,4.0,5,4.10,Left
1,2,26,MSc,4,BFSI,Oracle,SE,Citi Bank,4.0,4,3.15,Left
2,3,24,BE,2,BFSI,Java,SE,Bank of America,2.5,4,3.30,Left
3,4,31,MCA,9,Telecom,C++,Lead,Erickson,10.0,4,3.03,Left
4,5,30,Mtech,7,Telecom,Networking,Lead,Erickson,10.0,5,3.40,Left

In [9]:
df2 = pd.get_dummies(df1['Status'])

In [13]:
df1.drop('Status',axis = 1)

,Serial No,Age,Qualification,Experience,Domain,Skill,Designation,Project,Salary,Rating,ESS,Left,Not Left
0,1,25,MCA,3,BFSI,Java,SE,Citi Bank,4.0,5,4.10,1,0
1,2,26,MSc,4,BFSI,Oracle,SE,Citi Bank,4.0,4,3.15,1,0
2,3,24,BE,2,BFSI,Java,SE,Bank of America,2.5,4,3.30,1,0
3,4,31,MCA,9,Telecom,C++,Lead,Erickson,10.0,4,3.03,1,0
4,5,30,Mtech,7,Telecom,Networking,Lead,Erickson,10.0,5,3.40,1,0
5,6,27,BE,5,BFSI,Java,SSE,Bank of America,4.0,3,2.90,1,0
6,7,30,Graduate,8,BFSI,Mainframe,SSE,Wells Farago,6.0,3,3.00,1,0
7,8,31,Graduate,8,Telecom,C++,SSE,Erickson,6.0,3,3.10,1,0
8,9,27,Mtech,2,Telecom,Networking,SE,Erickson,4.0,5,3.20,1,0
9,10,24,MCA,2,BFSI,Java,SE,Citi Bank,3.0,4,3.30,1,0
10,11,29,CA,5,Manufacturing,SAP(F),SSE,Coca Cola,8.0,4,3.10,1,0
11,12,31,MCA,8,Manufacturing,SAP(T),SSE,Apple,8.0,3,3.00,1,0
12,13,33,MCA,10,BFSI,Java,Lead,Citi Bank,12.0,2,3.40,1,0
13,14,25,MCA,3,BFSI,Java,SE,Citi Bank,4.0,5,4.10,1,0
14,15,26,MSc,4,BFSI,Oracle,SE,Citi Bank,4.0,4,3.15,1,0
15,16,24,BE,2,BFSI,Java,SE,Bank of America,2.5,4,3.30,1,0
16,17,31,MCA,9,Telecom,C++,Lead,Erickson,10.0,4,3.03,1,0
17,18,30,MCA,7,Telecom,Networking,Lead,Erickson,10.0,5,3.40,1,0
18,19,27,BE,5,BFSI,Java,SSE,Bank of America,4.0,3,2.90,1,0
19,20,30,Graduate,8,BFSI,Mainframe,SSE,Wells Farago,6.0,3,3.00,1,0
20,21,31,Graduate,8,Telecom,C++,SSE,Erickson,6.0,3,3.10,1,0
21,22,27,Mtech,2,Telecom,Networking,SE,Erickson,4.0,5,3.20,1,0
22,23,24,MCA,2,BFSI,Java,SE,Citi Bank,3.0,4,3.30,1,0
23,24,29,CA,5,Manufacturing,SAP(F),SSE,Coca Cola,8.0,4,3.10,1,0
24,25,31,MCA,8,Manufacturing,SAP(T),SSE,Coca Cola,8.0,3,3.00,1,0
25,26,35,BSc,14,BFSI,Java,SSE,Citi Bank,11.0,3,4.20,0,1
26,27,29,MSc,7,BFSI,Oracle,Lead,Citi Bank,11.0,4,3.50,0,1
27,28,24,BE,2,BFSI,Java,SE,Bank of America,2.5,4,3.40,0,1
28,29,31,BSc,9,Telecom,C++,Lead,Erickson,10.0,4,3.60,0,1
29,30,30,BE,8,Telecom,Networking,Lead,Erickson,9.0,3,3.40,0,1
30,31,27,BE,5,BFSI,Java,SSE,Bank of America,4.0,3,3.10,0,1
31,32,30,Graduate,8,BFSI,Mainframe,SSE,Wells Farago,6.0,3,3.20,0,1
32,33,31,Graduate,8,Telecom,C++,SSE,Erickson,6.0,3,3.15,0,1
33,34,27,Mtech,2,Telecom,Networking,SE,Erickson,4.0,5,3.45,0,1
34,35,24,MSc,2,BFSI,Java,SE,Citi Bank,3.0,4,3.30,0,1
35,36,29,MBA,5,Manufacturing,SAP(F),SSE,Apple,8.0,4,3.10,0,1
36,37,31,BE,8,Manufacturing,SAP(T),SSE,Apple,8.0,3,3.00,0,1
37,38,33,BE,10,BFSI,Java,Lead,Citi Bank,13.0,2,3.40,0,1
38,39,30,MCA,8,BFSI,Java,Lead,Citi Bank,11.0,4,4.10,0,1
39,40,26,MSc,4,BFSI,Oracle,SE,Citi Bank,4.0,4,3.15,0,1
40,41,24,BE,2,BFSI,Java,SE,Bank of America,2.5,4,3.30,0,1
41,42,31,MCA,9,Telecom,C++,Lead,Erickson,10.0,4,3.05,0,1
42,43,30,MCA,9,Telecom,Networking,Lead,Erickson,10.0,4,3.40,0,1
43,44,27,BE,5,BFSI,Java,SSE,Bank of America,4.0,3,3.15,0,1
44,45,35,Graduate,13,BFSI,Mainframe,SSE,Wells Farago,10.0,3,3.30,0,1
45,46,31,Graduate,8,Telecom,C++,SSE,Erickson,6.0,3,3.10,0,1
46,47,28,Mtech,3,Telecom,Networking,SE,Erickson,4.0,3,3.20,0,1
47,48,24,MSc,2,BFSI,Java,SE,Citi Bank,3.5,4,3.30,0,1
48,49,39,Mcom,15,Manufacturing,SAP(F),Lead,Coca Cola,15.0,3,3.40,0,1
49,50,31,MBA,8,Manufacturing,SAP(T),SSE,Coca Cola,11.0,3,3.30,0,1

In [11]:
df1 = df1.join(df2)

In [15]:
corr = df1.corr()

In [16]:
corr

,Serial No,Age,Experience,Salary,Rating,ESS,Left,Not Left
Serial No,1.000000,0.247025,0.226894,0.225267,-0.278286,0.037205,-0.866199,0.866199
Age,0.247025,1.000000,0.956044,0.869285,-0.509858,0.003936,-0.205777,0.205777
Experience,0.226894,0.956044,1.000000,0.857237,-0.551027,0.068844,-0.229986,0.229986
Salary,0.225267,0.869285,0.857237,1.000000,-0.298450,0.183772,-0.217435,0.217435
Rating,-0.278286,-0.509858,-0.551027,-0.298450,1.000000,0.314379,0.235460,-0.235460
ESS,0.037205,0.003936,0.068844,0.183772,0.314379,1.000000,-0.202567,0.202567
Left,-0.866199,-0.205777,-0.229986,-0.217435,0.235460,-0.202567,1.000000,-1.000000
Not Left,0.866199,0.205777,0.229986,0.217435,-0.235460,0.202567,-1.000000,1.000000