In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'A': [1,2,3,1], 'B': [2,1,3,3], 'C': [3,2,1,4]})
df

   A  B  C
0  1  2  3
1  2  1  2
2  3  3  1
3  1  3  4

In [3]:
out_df = pd.DataFrame({'A': [1], 'B': [2], 'C': [3]})
out_df

   A  B  C
0  1  2  3

In [13]:
condition_dict_1 = {'A': 1, 'B': 2, 'C': 3}
keys = condition_dict_1.keys()
col_list = list(keys)
col_list[0]

'A'

In [14]:
condition_dict_1['A']

1

In [16]:
print(f'col_{1}')

col_1

In [18]:
len(col_list)

3

In [ ]:
keys = condition_dict_1.keys()
col_list = list(keys)

A 1
B 2
C 3

In [40]:
for i,j in condition_dict_1.items():
    print(i,j)

A 1
B 2
C 3

In [44]:
from functools import reduce

mask = reduce(lambda a, b: a & b, [df[col] == val for col, val in condition_dict_1.items()])
df[mask]
# print(mask)

   A  B  C
0  1  2  3

In [37]:
keys = condition_dict_1.keys()
col_list = list(keys)

condition = ""
for i in range(0, len(col_list)): 
    col_name = "col" + str(i)
    val_name = "val" + str(i)
    col_name = col_list[i]

    val_name = condition_dict_1[col_name]

    
    # print(cond)

    if i == len(col_list)-1:
        cond = "(df['" + str(col_name)+ "']==" + str(val_name) + ")"
        condition  += str(cond)

    else:
        cond = "(df['" + str(col_name)+ "']==" + str(val_name) + ")&"
        condition += str(cond)

    # return df[condition]


    # print(col_name ,val_name )
# print(condition)

df[eval(condition)]

   A  B  C
0  1  2  3

In [ ]:
df[(df['col1']== 1) & (df['col2']== 1)]

In [35]:
#Question
#Dictionary of Conditions
condition_dict_1 = {'A': 1, 'B': 2, 'C': 3}
#Input DataFrame
df = pd.DataFrame({'A': [1,2,3,1], 'B': [2,1,3,3], 'C': [3,2,1,4]})
#Filter out all rows from input dataframe which satisfy all conditions in the dict. 
# In this case, the conditions are all rows where column A has value 1, column B has value 2 and column C has value 3.

 
def filter_df(df, dict1):
    keys = condition_dict_1.keys()
    col_list = list(keys)

    condition = "["
    for i in range(0, len(col_list)): 
        col_name = "col" + str(i)
        val_name = "val" + str(i)
        col_name = col_list[i]

        val_name = condition_dict_1[col_name]

        
        # print(cond)

        if i == len(col_list)-1:
            cond = "(df['" + str(col_name)+ "']==" + str(val_name) + ")]"
            condition  += str(cond)

        else:
            cond = "(df['" + str(col_name)+ "']==" + str(val_name) + ")&"
            condition += str(cond)

        # return df[condition]


        # print(col_name ,val_name )
    # print(condition)

    df[condition]
 

    # return df_output
 
df = pd.DataFrame({'A': [1,2,3,1], 'B': [2,1,3,3], 'C': [3,2,1,4]})
conditions = {'A': 1, 'B': 2, 'C': 3}
output = filter_df(df, conditions )
 
# Output:
out_df = pd.DataFrame({'A': [1], 'B': [2], 'C': [3]})

KeyError: "[(df['A']==1)&(df['B']==2)&(df['C']==3)]"